services:
  - type: web
    name: food-ordering-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: FLASK_ENV
        value: production
